# [package]
# name = "CourseDDBS"
# version = "0.1.0"
# edition = "2021"

[workspace]
members = [
    "src/common",
    "src/repl",
    "src/runserver",
    "src/protos",
    
    "src/control",
    "src/dbserver",

    "tests",
]
