services:
  namenode:
    image: hdfs-namenode
    ports:
      - "8020:8020"
      - "9870:9870"
    networks:
      - ddbms-network
  datanode1:
    image: hdfs-base
    command: hdfs datanode
    networks:
      - ddbms-network
  datanode2:
    image: hdfs-base
    command: hdfs datanode
    networks:
      - ddbms-network
  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql1
    networks:
      - ddbms-network
  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql2
    networks:
      - ddbms-network

networks:
  ddbms-network:
    driver: bridge