[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
toml = "0.5"
mysql = "23.0.0"
thiserror = "1.0"
sqlparser = "0.27"
serde = { version = "1.0", features = ["derive"] }
flexbuffers = "2.0"
futures = "0.3"
pin-project = "1.0"
time = "0.3"