[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "../protos" }
tokio = { version = "1.11", features = ["fs"] }
tonic = { version = "0.6", features = ["tls"] }